#Exchanges
MAIN_EXCHANGE_NAME="main"

#Queues
SCORING_MANAGER_QUEUE="scoring_manager_queue"

SOURCES_MANAGER_QUEUE="sources_manager_queue"

WILLZ_STATUS_UPDATER_QUEUE="willz_status_updater_queue"

CHECKS_PROCESSOR_QUEUE="checks_manager_queue"
CLIENT_PROCESSOR_QUEUE="client_processor_queue"

SCORING_PROCESSOR_QUEUE="scoring_processor_queue"

SCORISTA_PROCESSOR_QUEUE="scorista_processor_queue"

##Messages
CLIENT_RAW_CREATED_MESSAGE="client_raw_created"

CLIENT_PROCESSED_MESSAGE="client_processed"

CLIENT_SCORING_COMPLETE_MESSAGE="client_scoring_complete"

INDIVIDUAL_CHECKS_PROCESS_MESSAGE="individual_checks_process"
INDIVIDUAL_CHECKS_PROCESSED_MESSAGE="individual_checks_processed"

INDIVIDUAL_SCORING_PROCESS="individual_scoring_process"
INDIVIDUAL_SCORING_PROCESSED_MESSAGE="individiual_scoring_processed"

INDIVIDUAL_SOURCES_PROCESS_MESSAGE="individiual_process_sources"
INDIVIDUAL_SOURCES_PROCESSED_MESSAGE="individiual_sources_processed"

SCORISTA_SOURCE_PROCESS_MESSAGE="individual_scorista_source_process"
SCORISTA_SOURCE_PROCESSED_MESSAGE="individual_scorista_source_processed"

CLIENT_PROCESSOR_NAME = "New Client Processor"
